# Project Milestone Two: Modeling and Feature Engineering

### Due: Midnight on April 13 (with 2-hour grace period) and worth 25 points

### Overview

This milestone builds on your work from Milestone 1. You will:

1. Evaluate baseline models using default settings.
2. Engineer new features and re-evaluate models.
3. Use feature selection techniques to find promising subsets.
4. Select the top 3 models and fine-tune them for optimal performance.

You must do all work in this notebook and upload to your team leader's account in Gradescope. There is no
Individual Assessment for this Milestone. 


In [1]:
# ===================================
# Useful Imports: Add more as needed
# ===================================

# Standard Libraries
import os
import time
import math
import io
import zipfile
import requests
from urllib.parse import urlparse
from itertools import chain, combinations

# Data Science Libraries
import numpy as np
import pandas as pd
import seaborn as sns

# Visualization
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.ticker as mticker  # Optional: Format y-axis labels as dollars
import seaborn as sns

# Scikit-learn (Machine Learning)
from sklearn.model_selection import (
    train_test_split, 
    cross_val_score, 
    GridSearchCV, 
    RandomizedSearchCV, 
    RepeatedKFold
)
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error
from sklearn.feature_selection import SequentialFeatureSelector, f_regression, SelectKBest
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor, GradientBoostingRegressor

# Progress Tracking

from tqdm import tqdm

# =============================
# Global Variables
# =============================
random_state = 42

# =============================
# Utility Functions
# =============================

# Format y-axis labels as dollars with commas (optional)
def dollar_format(x, pos):
    return f'${x:,.0f}'

# Convert seconds to HH:MM:SS format
def format_hms(seconds):
    return time.strftime("%H:%M:%S", time.gmtime(seconds))



## Prelude: Load your Preprocessed Dataset from Milestone 1

In Milestone 1, you handled missing values, encoded categorical features, and explored your data. Before you begin this milestone, you’ll need to load that cleaned dataset and prepare it for modeling.

Here’s what to do:

1. Return to your Milestone 1 notebook and rerun your code through Part 3, where your dataset was fully cleaned (assume it’s called `df_cleaned`).

2. **Save** the cleaned dataset to a file by running:

>   df_cleaned.to_csv("zillow_cleaned.csv", index=False)

3. Switch to this notebook and **load** the saved data:

>   df = pd.read_csv("zillow_cleaned.csv")

4. Create a **train/test split** using `train_test_split`.  
   
6. **Standardize** the features (but not the target!) using **only the training data.** This ensures consistency across models without introducing data leakage from the test set:

>   scaler = StandardScaler()   
>   X_train_scaled = scaler.fit_transform(X_train)    
  
**Notes:** 

- You will not use the testing set during this milestone — it’s reserved for final evaluation later.
- You will have to redo the scaling step when you introduce new features (which have to be scaled as well).


In [2]:
df = pd.read_csv("zillow_cleaned.csv")

In [3]:
df.isna().sum().sum()

np.int64(0)

In [4]:
# Add as many code cells as you need
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop('taxvaluedollarcnt', axis=1)  
y = df['taxvaluedollarcnt']  


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)




### Part 1: Baseline Modeling [3 pts]

Apply the following regression models to the scaled training dataset using **default parameters**:

- Linear Regression
- Ridge Regression
- Lasso Regression
- Decision Tree Regression
- Bagging
- Random Forest
- Gradient Boosting Trees

For each model:
- Use **repeated cross-validation** (e.g., 5 folds, 5 repeats).
- Report the **mean and standard deviation of CV RMSE Score** across all folds in a table. 


In [5]:
# Add as many code cells as you need

#Linear Regression

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score, RepeatedKFold


model = LinearRegression()

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

linear_reg_results = {
    'Model': 'Linear Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}




In [6]:
# Ridge

from sklearn.linear_model import Ridge

model = Ridge()

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

ridge_reg_results = {
    'Model': 'Ridge Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

In [7]:
# Lasso
from sklearn.linear_model import Lasso

model = Lasso()

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

lasso_reg_results = {
    'Model': 'Lasso Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.833e+15, tolerance: 2.313e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.104e+15, tolerance: 2.701e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duali

In [8]:
# Decision Tree 

from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

decision_tree_results = {
    'Model': 'Decision Tree Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

In [9]:
# Bagging 

from sklearn.ensemble import BaggingRegressor

model = BaggingRegressor()
cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

bagging_results = {
    'Model': 'Bagging Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [10]:
# Random Forest 

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=10, max_depth=10, n_jobs=-1, random_state=42)

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

random_forest_results = {
    'Model': 'Random Forest Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [11]:
#Gradient Boosting

model = GradientBoostingRegressor(
    n_estimators=100,        
    max_depth=3,             
    learning_rate=0.05,     
    random_state=42          
)

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X, y, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)  
std_rmse = np.std(cv_results)

gradient_boosting_results = {
    'Model': 'Gradient Boosting Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [12]:
results = [
    linear_reg_results,
    ridge_reg_results,
    lasso_reg_results,
    decision_tree_results,
    bagging_results,
    random_forest_results,
    gradient_boosting_results
]

results_df = pd.DataFrame(results)
print(results_df)


                         Model      Mean RMSE      Std RMSE
0            Linear Regression  510577.122282  55441.756243
1             Ridge Regression  509605.296441  55120.462340
2             Lasso Regression  510561.302332  55437.863581
3      Decision Tree Regressor  648524.745228  52524.808295
4            Bagging Regressor  496993.129673  50491.946785
5      Random Forest Regressor  490369.367314  50403.779666
6  Gradient Boosting Regressor  487584.823330  51213.798501


### Part 1: Discussion [2 pts]

In a paragraph or well-organized set of bullet points, briefly compare and discuss:

  - Which models perform best overall?
  - Which are most stable (lowest std)?
  - Any signs of overfitting or underfitting?

To determine which model performed best, we looked at Mean RMSE of each model; the lower this value, the better the model performed. Therefore, according to our results, Random Forest Regressor (Mean RMSE: 490369.367314) was the best model in part 1. However, this score is still a very large number and is concerning in terms of our model's accuracy in predicting the target value. When looking at which model is the most stable (or has the lowest std), we see the Random Forest Regressor is again the best option. This model has a STD of 50403.779666 which indictates it fits the data the most consistently (compared to the other models) and there are not major outliers effecting the performance of the model. Based on the results, we would say the Decision Tree Regression model is underfitting the data. The model resulted in a large Mean RMSE value and a fairly standard STD which signifies it may not be capturing the complexity of the training data even though the errors tend to be consistent across the data. This model will mostly likely not generalize well to unseen data.

### Part 2: Feature Engineering [3 pts]

Consider **at least three new features** based on your Milestone 1, Part 5. Examples include:
- Polynomial terms
- Log or interaction terms
- Groupings or transformations of categorical features

Add these features to `X_train` and then:
- Scale using `StandardScaler` 
- Re-run all models listed above (using default settings again).
- Report updated RMSE scores (mean and std) across repeated CV in a table. 

**Note:**  Recall that this will require creating a new version of the dataset, so effectively you may be running "polynomial regression" using `LinearRegression`. 

In [13]:
# Add as many code cells as you need

from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X_train)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_poly_scaled = scaler.fit_transform(X_poly)



In [14]:
# Linear Regression and Polynomial Features

model = LinearRegression()

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)  
std_rmse = np.std(cv_results)

# Store results in dictionary
linear_regression_poly_results = {
    'Model': 'Linear Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [15]:
# Ridge Regression model and Polynomial Features

model = Ridge()
cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

ridge_regression_poly_results = {
    'Model': 'Ridge Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [16]:
# Lasso Regression model and Polynomial Features

model = Lasso(alpha=0.01, max_iter=1000, random_state=42)
cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)  
std_rmse = np.std(cv_results)

lasso_poly_results = {
    'Model': 'Lasso Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}




/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.654e+15, tolerance: 1.775e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.082e+15, tolerance: 1.882e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duali

In [17]:
# Decision Tree Regressor model and Polynomial Features

model = DecisionTreeRegressor(
    max_depth=10,  
    min_samples_split=10,  
    min_samples_leaf=5,  
    max_features='sqrt',  
    random_state=42
)

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)  
std_rmse = np.std(cv_results)

decision_tree_poly_results = {
    'Model': 'Decision Tree Regressor (Polynomial Features)',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [18]:
# Bagging Regressor model and Polynomial Features

model = BaggingRegressor(
    estimator=LinearRegression(),  
    n_estimators=50, 
    max_samples=0.8,  
    max_features=0.8,  
    n_jobs=1,  
    random_state=42
)

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)
cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results) 
std_rmse = np.std(cv_results)

bagging_with_poly_results = {
    'Model': 'Bagging Regressor (Linear Regression as base estimator)',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}



In [19]:
# Random Forest Regressor model and Polynomial Features

model = RandomForestRegressor(n_estimators=50, max_depth=10, max_features='sqrt', n_jobs=-1, random_state=42)

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

random_forest_poly_results = {
    'Model': 'Random Forest Regressor (Polynomial Features)',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}




In [20]:
# Gradient Boosting Regressor model and Polynomial Features

model = GradientBoostingRegressor(
    n_estimators=100,  
    max_depth=3,       
    learning_rate=0.05, 
    max_features='sqrt', 
    random_state=42,
)

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)
cv_results = cross_val_score(model, X_poly_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)  
std_rmse = np.std(cv_results)

gradient_boosting_poly_results = {
    'Model': 'Gradient Boosting Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

In [21]:
# Results of all models with Polynomial Features 

all_results = [
    linear_regression_poly_results,
    ridge_regression_poly_results,
    lasso_poly_results,
    decision_tree_poly_results,
    bagging_with_poly_results,
    random_forest_poly_results,
    gradient_boosting_poly_results
]

results_poly_df = pd.DataFrame(all_results)

print(results_poly_df)


                                               Model     Mean RMSE  \
0                                  Linear Regression  4.903596e+16   
1                                   Ridge Regression  6.427891e+05   
2                                   Lasso Regression  1.740171e+06   
3      Decision Tree Regressor (Polynomial Features)  4.823580e+05   
4  Bagging Regressor (Linear Regression as base e...  9.360767e+15   
5      Random Forest Regressor (Polynomial Features)  4.431714e+05   
6                        Gradient Boosting Regressor  4.515705e+05   

       Std RMSE  
0  1.487926e+17  
1  3.850236e+05  
2  4.298589e+06  
3  2.388581e+04  
4  1.299023e+16  
5  2.098438e+04  
6  2.152383e+04  


In [22]:
X_log = np.log1p(X_train)  
scaler = StandardScaler()
X_log_scaled = scaler.fit_transform(X_log)

In [23]:
# Linear Regression + Log


model = LinearRegression()
cv = RepeatedKFold(n_splits=3, n_repeats=3, random_state=42)
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=1)

mean_rmse = -np.mean(cv_results)  
std_rmse = np.std(cv_results)

linear_regression_log_results = {
    'Model': 'Linear Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [24]:
# Ridge + Log 

model = Ridge()
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)
ridge_regression_log_results = {
    'Model': 'Ridge Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [25]:
# Lasso + Log

model = Lasso(alpha=0.01, max_iter=1000, random_state=42)
cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

lasso_regression_log_results = {
    'Model': 'Lasso Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.781e+15, tolerance: 1.882e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.268e+15, tolerance: 1.775e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duali

In [26]:
# Decision Tree + Log

model = DecisionTreeRegressor(
    max_depth=10,  
    min_samples_split=10,  
    min_samples_leaf=5,  
    max_features='sqrt',  
    random_state=42
)
cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)
decision_tree_log_results = {
    'Model': 'Decision Tree Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [27]:
# Bagging + Log

model = BaggingRegressor(
    estimator=LinearRegression(),  
    n_estimators=50, 
    max_samples=0.8,  
    max_features=0.8,  
    n_jobs=1,  
    random_state=42
)
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)
bagging_log_results = {
    'Model': 'Bagging Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

In [28]:
# Random Forest + Log

model = RandomForestRegressor(n_estimators=50, max_depth=10, max_features='sqrt', n_jobs=-1, random_state=42)
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)
random_forest_log_results = {
    'Model': 'Random Forest Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

In [29]:
# Gradient Boosting + Log
model = GradientBoostingRegressor(
    n_estimators=100,  
    max_depth=3,       
    learning_rate=0.05, 
    max_features='sqrt', 
    random_state=42,
)
cv_results = cross_val_score(model, X_log_scaled, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)
mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)
gradient_boosting_log_results = {
    'Model': 'Gradient Boosting Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}

In [30]:
# Results of all models with Log-Transformation
all_log_results = [
    linear_regression_log_results,
    ridge_regression_log_results,
    lasso_regression_log_results,
    decision_tree_log_results,
    bagging_log_results,
    random_forest_log_results,
    gradient_boosting_log_results
]

log_results_df = pd.DataFrame(all_log_results)

print(log_results_df)


                         Model     Mean RMSE      Std RMSE
0            Linear Regression  1.396560e+16  2.310297e+16
1             Ridge Regression  5.177330e+05  1.412802e+04
2             Lasso Regression  5.171367e+05  2.675906e+04
3      Decision Tree Regressor  4.827858e+05  1.961538e+04
4            Bagging Regressor  3.982166e+13  1.950855e+14
5      Random Forest Regressor  4.458714e+05  2.060293e+04
6  Gradient Boosting Regressor  4.552258e+05  2.164246e+04


In [31]:
import pandas as pd

cat_columns = df.select_dtypes(include=['object', 'category']).columns
df_encoded = pd.get_dummies(df, columns=cat_columns)


In [32]:
# Linear Regression + One-Hot Encoding 


X_onehot = df_encoded.drop('taxvaluedollarcnt', axis=1)  
y_train_onehot = df_encoded['taxvaluedollarcnt']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_onehot)

model = LinearRegression()
cv = 5  
cv_results = cross_val_score(model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=1)

mean_rmse = -np.mean(cv_results)
std_rmse = np.std(cv_results)

linear_regression_onehot_results = {
    'Model': 'Linear Regression',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [33]:
# Ridge + One-Hot Encoding 

ridge_model = Ridge()
cv_results_ridge = cross_val_score(ridge_model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

mean_rmse_ridge = -np.mean(cv_results_ridge) 
std_rmse_ridge = np.std(cv_results_ridge)

ridge_regression_onehot_results = {
    'Model': 'Ridge Regression',
    'Mean RMSE': mean_rmse_ridge,
    'Std RMSE': std_rmse_ridge
}


In [34]:
# Lasso + One-Hot Encoding 

lasso_model = Lasso()
cv_results_lasso = cross_val_score(lasso_model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=5, n_jobs=-1)
mean_rmse_lasso = -np.mean(cv_results_lasso)
std_rmse_lasso = np.std(cv_results_lasso)

lasso_regression_onehot_results = {
    'Model': 'Lasso Regression',
    'Mean RMSE': mean_rmse_lasso,
    'Std RMSE': std_rmse_lasso
}


/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.347e+15, tolerance: 2.726e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.306e+12, tolerance: 2.432e+12
  model = cd_fast.enet_coordinate_descent(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duali

In [35]:
# Decision Tree + One-Hot Encoding 

dt_model = DecisionTreeRegressor(random_state=42)
cv_results_dt = cross_val_score(dt_model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=5, n_jobs=-1)
mean_rmse_dt = -np.mean(cv_results_dt)
std_rmse_dt = np.std(cv_results_dt)

decision_tree_onehot_results = {
    'Model': 'Decision Tree Regressor',
    'Mean RMSE': mean_rmse_dt,
    'Std RMSE': std_rmse_dt
}

In [36]:
# Bagging + One-Hot Encoding 

bagging_model = BaggingRegressor(estimator=LinearRegression(), n_estimators=50, random_state=42)
cv_results_bagging = cross_val_score(bagging_model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=5, n_jobs=-1)
mean_rmse_bagging = -np.mean(cv_results_bagging)
std_rmse_bagging = np.std(cv_results_bagging)

bagging_onehot_results = {
    'Model': 'Bagging Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}



In [37]:
# Random Forest + One-Hot Encoding 

rf_model = RandomForestRegressor(random_state=42)

cv_results_rf = cross_val_score(rf_model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=5, n_jobs=-1)

mean_rmse_rf = -np.mean(cv_results_rf)
std_rmse_rf = np.std(cv_results_rf)

random_forest_onehot_results = {
    'Model': 'Random Forest Regressor',
    'Mean RMSE': mean_rmse_rf,
    'Std RMSE': std_rmse_rf
}




In [38]:
# Gradient Boosting + One-Hot Encoding 


gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

cv_results_gb = cross_val_score(gb_model, X_scaled, y_train_onehot, scoring='neg_root_mean_squared_error', cv=5, n_jobs=-1)

mean_rmse_gb = -np.mean(cv_results_gb)
std_rmse_gb = np.std(cv_results_gb)

gradient_boosting_onehot_results = {
    'Model': 'Gradient Boosting Regressor',
    'Mean RMSE': mean_rmse,
    'Std RMSE': std_rmse
}


In [39]:
# Results of all models with One-Hot Encoding 
all_encoded_results = [
    linear_regression_onehot_results,
    ridge_regression_onehot_results,
    lasso_regression_onehot_results,
    decision_tree_onehot_results,
    bagging_onehot_results,
    random_forest_onehot_results,
    gradient_boosting_onehot_results
]

encoded_results_df = pd.DataFrame(all_encoded_results)
print(encoded_results_df)


                         Model     Mean RMSE      Std RMSE
0            Linear Regression  8.754466e+14  1.750893e+15
1             Ridge Regression  5.103745e+05  4.797900e+04
2             Lasso Regression  5.103837e+05  4.797581e+04
3      Decision Tree Regressor  6.401002e+05  3.837229e+04
4            Bagging Regressor  8.754466e+14  1.750893e+15
5      Random Forest Regressor  4.813342e+05  4.627292e+04
6  Gradient Boosting Regressor  8.754466e+14  1.750893e+15


In [40]:
print("Baseline Modeling:")
print(results_df)

print("Polynomial:")
print(results_poly_df)

print("\nLog Results:")
print(log_results_df)

print("\One-Hot Results:")
print(encoded_results_df)


Baseline Modeling:
                         Model      Mean RMSE      Std RMSE
0            Linear Regression  510577.122282  55441.756243
1             Ridge Regression  509605.296441  55120.462340
2             Lasso Regression  510561.302332  55437.863581
3      Decision Tree Regressor  648524.745228  52524.808295
4            Bagging Regressor  496993.129673  50491.946785
5      Random Forest Regressor  490369.367314  50403.779666
6  Gradient Boosting Regressor  487584.823330  51213.798501
Polynomial:
                                               Model     Mean RMSE  \
0                                  Linear Regression  4.903596e+16   
1                                   Ridge Regression  6.427891e+05   
2                                   Lasso Regression  1.740171e+06   
3      Decision Tree Regressor (Polynomial Features)  4.823580e+05   
4  Bagging Regressor (Linear Regression as base e...  9.360767e+15   
5      Random Forest Regressor (Polynomial Features)  4.431714e+05   

<>:10: SyntaxWarning: invalid escape sequence '\O'
<>:10: SyntaxWarning: invalid escape sequence '\O'
/tmp/ipykernel_1550/2689290080.py:10: SyntaxWarning: invalid escape sequence '\O'
  print("\One-Hot Results:")


In [43]:
total_results = [
    # Baseline Results
    {'Model': 'Linear Regression', 'Transformation': 'Baseline', 'Mean RMSE': 510577.122282, 'Std RMSE': 55441.756243},
    {'Model': 'Ridge Regression', 'Transformation': 'Baseline', 'Mean RMSE': 509605.296441, 'Std RMSE': 55120.462340},
    {'Model': 'Lasso Regression', 'Transformation': 'Baseline', 'Mean RMSE': 510561.302332, 'Std RMSE': 55437.863581},
    {'Model': 'Decision Tree Regressor', 'Transformation': 'Baseline', 'Mean RMSE': 648524.745228, 'Std RMSE': 52524.808295},
    {'Model': 'Bagging Regressor', 'Transformation': 'Baseline', 'Mean RMSE': 496993.129673, 'Std RMSE': 50491.946785},
    {'Model': 'Random Forest Regressor', 'Transformation': 'Baseline', 'Mean RMSE': 490369.367314, 'Std RMSE': 50403.779666},
    {'Model': 'Gradient Boosting Regressor', 'Transformation': 'Baseline', 'Mean RMSE': 487584.823330, 'Std RMSE': 51213.798501},
    
    # Polynomial Features Results
    {'Model': 'Linear Regression', 'Transformation': 'Polynomial', 'Mean RMSE': 4.903596e+16, 'Std RMSE': 1.487926e+17},
    {'Model': 'Ridge Regression', 'Transformation': 'Polynomial', 'Mean RMSE': 642789.130214, 'Std RMSE': 385023.566890},
    {'Model': 'Lasso Regression', 'Transformation': 'Polynomial', 'Mean RMSE': 1740170.665471, 'Std RMSE': 4298589.078269},
    {'Model': 'Decision Tree Regressor', 'Transformation': 'Polynomial', 'Mean RMSE': 482358.024753, 'Std RMSE': 23885.813204},
    {'Model': 'Bagging Regressor', 'Transformation': 'Polynomial', 'Mean RMSE': 9.360767e+15, 'Std RMSE': 1.299023e+16},
    {'Model': 'Random Forest Regressor', 'Transformation': 'Polynomial', 'Mean RMSE': 443171.361225, 'Std RMSE': 20984.384105},
    {'Model': 'Gradient Boosting Regressor', 'Transformation': 'Polynomial', 'Mean RMSE': 451570.468416, 'Std RMSE': 21523.826872},
    
    # Log Transformation Results
    {'Model': 'Linear Regression', 'Transformation': 'Log', 'Mean RMSE': 1.396560e+16, 'Std RMSE': 2.310297e+16},
    {'Model': 'Ridge Regression', 'Transformation': 'Log', 'Mean RMSE': 517733.034511, 'Std RMSE': 14128.023938},
    {'Model': 'Lasso Regression', 'Transformation': 'Log', 'Mean RMSE': 517136.680219, 'Std RMSE': 26759.060225},
    {'Model': 'Decision Tree Regressor', 'Transformation': 'Log', 'Mean RMSE': 482785.803915, 'Std RMSE': 19615.375937},
    {'Model': 'Bagging Regressor', 'Transformation': 'Log', 'Mean RMSE': 3.982166e+13, 'Std RMSE': 1.950855e+14},
    {'Model': 'Random Forest Regressor', 'Transformation': 'Log', 'Mean RMSE': 445871.421125, 'Std RMSE': 20602.932080},
    {'Model': 'Gradient Boosting Regressor', 'Transformation': 'Log', 'Mean RMSE': 455225.820086, 'Std RMSE': 21642.463239},
    
    # One-Hot Encoding Results
    {'Model': 'Linear Regression', 'Transformation': 'One-Hot', 'Mean RMSE': 8.754466e+14, 'Std RMSE': 1.750893e+15},
    {'Model': 'Ridge Regression', 'Transformation': 'One-Hot', 'Mean RMSE': 510374.508113, 'Std RMSE': 47979.004181},
    {'Model': 'Lasso Regression', 'Transformation': 'One-Hot', 'Mean RMSE': 510383.674347, 'Std RMSE': 47975.805231},
    {'Model': 'Decision Tree Regressor', 'Transformation': 'One-Hot', 'Mean RMSE': 640100.168755, 'Std RMSE': 38372.290709},
    {'Model': 'Bagging Regressor', 'Transformation': 'One-Hot', 'Mean RMSE': 8.754466e+14, 'Std RMSE': 1.750893e+15},
    {'Model': 'Random Forest Regressor', 'Transformation': 'One-Hot', 'Mean RMSE': 481334.234232, 'Std RMSE': 46272.918974},
    {'Model': 'Gradient Boosting Regressor', 'Transformation': 'One-Hot', 'Mean RMSE': 8.754466e+14, 'Std RMSE': 1.750893e+15}
]

df_total_results = pd.DataFrame(total_results)

comparison_table = df_total_results.pivot_table(
    index='Model', 
    columns='Transformation', 
    values=['Mean RMSE', 'Std RMSE'], 
    aggfunc='first'
)

print(comparison_table.to_string())

                                 Mean RMSE                                                Std RMSE                                          
Transformation                    Baseline           Log       One-Hot    Polynomial      Baseline           Log       One-Hot    Polynomial
Model                                                                                                                                       
Bagging Regressor            496993.129673  3.982166e+13  8.754466e+14  9.360767e+15  50491.946785  1.950855e+14  1.750893e+15  1.299023e+16
Decision Tree Regressor      648524.745228  4.827858e+05  6.401002e+05  4.823580e+05  52524.808295  1.961538e+04  3.837229e+04  2.388581e+04
Gradient Boosting Regressor  487584.823330  4.552258e+05  8.754466e+14  4.515705e+05  51213.798501  2.164246e+04  1.750893e+15  2.152383e+04
Lasso Regression             510561.302332  5.171367e+05  5.103837e+05  1.740171e+06  55437.863581  2.675906e+04  4.797581e+04  4.298589e+06
Linear Regres

### Part 2: Discussion [2 pts]

Reflect on the impact of your new features:

- Did any models show notable improvement in performance?
- Which new features seemed to help — and in which models?
- Do you have any hypotheses about why a particular feature helped (or didn’t)?
- Were there any unexpected results?

When looking at Log transformation, the Decision Tree Regressor,  Gradient Boosting Regressor, and Random Forest Regressor all showed improvements in performance; there was a reduction in Mean RMSE for each of these models and a large reduction is each model's std RMSE. This indicates the models improved in accuracy and consistency; the models were able to stabilize the variance in the data, reducing the effect the outliers have on the model, helping the model generalize more effectively. For One-Hot encoding, none of the models Mean RMSE significantly improved; they either performed slightly worse or stay about the same as the baseline. However, Decision Tree Regressor, Random Forest Regressor, Lasso Regression, and Ridge Regression all did some large improvements in the std RMSE. This is telling us these models may be overfitting the data, but because the mean RMSE did not change dramatically, it most likely is an indictation that the model's overall performance has become more consistent. Lastly, the polynomial terms produced the same results as the Log Transformation - the Decision Tree Regressor,  Gradient Boosting Regressor, and Random Forest Regressor all showed improvements in performance based on their lower Mean RMSE value and significantly lowered std RMSE's. 

The log transformation helps reduce the skewness in data; it addresses outliers and assists in making their effect not so large in the analysis. For models that are largely sensitive to outliers, like Gradient Boosting and Ridge Regression, this was largely beneficial. For Linear Regression, the model performed worse with log transformation. Linear Regression, as expected, assumes linearity. However, log transformation can disrupt this assumption and harm the model's performance. For Polynomial features, Linear Regression performed poorly again. This is not surprising as this causes exponential increases and the linear regression model is prone to overfitting to the noise, and not fitting to the actual data. Tree models, however, are designed to handle more complex relationships and the exponential increase actually improved their performance. Lastly, for One-Hot Encoding, Ridge Regression and Lasso Regression both benefitted since both models are equip to regularize large amounts of data, which ensures they are less prone to overfitting and generalize to unseen data more effectively. However, once again, the increase number of features lead Linear Regression to perform poorly; the more features present, the more likely the model overfits as the presence of multicollinearity infulences the model's performance and analysis.

### Part 3: Feature Selection [3 pts]

Using the full set of features (original + engineered):
- Apply **feature selection** methods to investigate whether you can improve performance.
  - You may use forward selection, backward selection, or feature importance from tree-based models.
- For each model, identify the **best-performing subset of features**.
- Re-run each model using only those features.
- Report updated RMSE scores (mean and std) across repeated CV in a table.


### Part 3: Discussion [2 pts]

Analyze the effect of feature selection on your models:

- Did performance improve for any models after reducing the number of features?

- Which features were consistently retained across models?

- Were any of your newly engineered features selected as important?

- How did feature selection differ between linear and tree-based models?

> Your text here

### Part 4: Fine-Tuning Your Top 3 Models [6 pts]

In this final phase of Milestone 2, you’ll select and refine your **three most promising models and their corresponding data pipelines** based on everything you've done so far.

1. Choose the top 3 models based on performance and interpretability from earlier parts.
2. For each model:
   - Perform hyperparameter tuning using `sweep_parameters`, `GridSearchCV`, `RandomizedSearchCV`, or other techniques from previous homeworks. 
   - Experiment with different versions of your feature engineering and preprocessing — treat these as additional tunable components.
3. Report the mean and standard deviation of CV RMSE score for each model in a summary table.



In [ ]:
# Add as many code cells as you need

### Part 4: Discussion [4 pts]

Reflect on your tuning process and final results:

- What was your tuning strategy for each model? Why did you choose those hyperparameters?
- Did you find that certain types of preprocessing or feature engineering worked better with specific models?
- Provide a ranking of your three models and explain your reasoning — not just based on RMSE, but also interpretability, training time, or generalizability.
- Conclude by considering whether this workflow has produced the results you expected. Typically, you would repeat steps 2 - 4 and also reconsider the choices you made in Milestone 1 when cleaning the dataset, until reaching the point of diminishing returns; do you think that would that have helped here?

> Your text here